name: 'pr-comment'
description: 'Adds pr changes as comment'
author: 'jis-wtag'

# Define your inputs here.
inputs:
  owner:
    description: 'The owner of the repository (user or org)'
    required: true
  repo:
    description: 'The repository name'
    required: true
  pr_number:
    description: 'The number of pull requests'
    required: true
  token:
    description: 'The token to use to access the GITHUB API'
    required: true

# Define your outputs here.

runs:
  using: node16
  main: dist/index.js
